/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as BookRouteImport } from './routes/book'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TreatmentsIndexRouteImport } from './routes/treatments.index'
import { Route as ConditionsIndexRouteImport } from './routes/conditions.index'
import { Route as TreatmentsSlugRouteImport } from './routes/treatments.$slug'
import { Route as ConditionsOsteoarthritisRouteImport } from './routes/conditions.osteoarthritis'
import { Route as ConditionsSlugRouteImport } from './routes/conditions.$slug'
import { Route as AboutTeamRouteImport } from './routes/about.team'
import { Route as AboutPracticeRouteImport } from './routes/about.practice'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsIndexRoute = TreatmentsIndexRouteImport.update({
  id: '/treatments/',
  path: '/treatments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsIndexRoute = ConditionsIndexRouteImport.update({
  id: '/conditions/',
  path: '/conditions/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsSlugRoute = TreatmentsSlugRouteImport.update({
  id: '/treatments/$slug',
  path: '/treatments/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsOsteoarthritisRoute =
  ConditionsOsteoarthritisRouteImport.update({
    id: '/conditions/osteoarthritis',
    path: '/conditions/osteoarthritis',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConditionsSlugRoute = ConditionsSlugRouteImport.update({
  id: '/conditions/$slug',
  path: '/conditions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutTeamRoute = AboutTeamRouteImport.update({
  id: '/about/team',
  path: '/about/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutPracticeRoute = AboutPracticeRouteImport.update({
  id: '/about/practice',
  path: '/about/practice',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/learning': typeof LearningRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about/practice': typeof AboutPracticeRoute
  '/about/team': typeof AboutTeamRoute
  '/conditions/$slug': typeof ConditionsSlugRoute
  '/conditions/osteoarthritis': typeof ConditionsOsteoarthritisRoute
  '/treatments/$slug': typeof TreatmentsSlugRoute
  '/conditions/': typeof ConditionsIndexRoute
  '/treatments/': typeof TreatmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/learning': typeof LearningRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about/practice': typeof AboutPracticeRoute
  '/about/team': typeof AboutTeamRoute
  '/conditions/$slug': typeof ConditionsSlugRoute
  '/conditions/osteoarthritis': typeof ConditionsOsteoarthritisRoute
  '/treatments/$slug': typeof TreatmentsSlugRoute
  '/conditions': typeof ConditionsIndexRoute
  '/treatments': typeof TreatmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/learning': typeof LearningRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about/practice': typeof AboutPracticeRoute
  '/about/team': typeof AboutTeamRoute
  '/conditions/$slug': typeof ConditionsSlugRoute
  '/conditions/osteoarthritis': typeof ConditionsOsteoarthritisRoute
  '/treatments/$slug': typeof TreatmentsSlugRoute
  '/conditions/': typeof ConditionsIndexRoute
  '/treatments/': typeof TreatmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/learning'
    | '/sitemap.xml'
    | '/about/practice'
    | '/about/team'
    | '/conditions/$slug'
    | '/conditions/osteoarthritis'
    | '/treatments/$slug'
    | '/conditions/'
    | '/treatments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/learning'
    | '/sitemap.xml'
    | '/about/practice'
    | '/about/team'
    | '/conditions/$slug'
    | '/conditions/osteoarthritis'
    | '/treatments/$slug'
    | '/conditions'
    | '/treatments'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/learning'
    | '/sitemap.xml'
    | '/about/practice'
    | '/about/team'
    | '/conditions/$slug'
    | '/conditions/osteoarthritis'
    | '/treatments/$slug'
    | '/conditions/'
    | '/treatments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  LearningRoute: typeof LearningRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AboutPracticeRoute: typeof AboutPracticeRoute
  AboutTeamRoute: typeof AboutTeamRoute
  ConditionsSlugRoute: typeof ConditionsSlugRoute
  ConditionsOsteoarthritisRoute: typeof ConditionsOsteoarthritisRoute
  TreatmentsSlugRoute: typeof TreatmentsSlugRoute
  ConditionsIndexRoute: typeof ConditionsIndexRoute
  TreatmentsIndexRoute: typeof TreatmentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments/': {
      id: '/treatments/'
      path: '/treatments'
      fullPath: '/treatments/'
      preLoaderRoute: typeof TreatmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions/': {
      id: '/conditions/'
      path: '/conditions'
      fullPath: '/conditions/'
      preLoaderRoute: typeof ConditionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments/$slug': {
      id: '/treatments/$slug'
      path: '/treatments/$slug'
      fullPath: '/treatments/$slug'
      preLoaderRoute: typeof TreatmentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions/osteoarthritis': {
      id: '/conditions/osteoarthritis'
      path: '/conditions/osteoarthritis'
      fullPath: '/conditions/osteoarthritis'
      preLoaderRoute: typeof ConditionsOsteoarthritisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions/$slug': {
      id: '/conditions/$slug'
      path: '/conditions/$slug'
      fullPath: '/conditions/$slug'
      preLoaderRoute: typeof ConditionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/team': {
      id: '/about/team'
      path: '/about/team'
      fullPath: '/about/team'
      preLoaderRoute: typeof AboutTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/practice': {
      id: '/about/practice'
      path: '/about/practice'
      fullPath: '/about/practice'
      preLoaderRoute: typeof AboutPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  LearningRoute: LearningRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AboutPracticeRoute: AboutPracticeRoute,
  AboutTeamRoute: AboutTeamRoute,
  ConditionsSlugRoute: ConditionsSlugRoute,
  ConditionsOsteoarthritisRoute: ConditionsOsteoarthritisRoute,
  TreatmentsSlugRoute: TreatmentsSlugRoute,
  ConditionsIndexRoute: ConditionsIndexRoute,
  TreatmentsIndexRoute: TreatmentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
